# Find more information on toml format here:  https://github.com/toml-lang/toml

# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"
loaderVersion="[26,)"

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
modId="tryingout"
version="${file.jarVersion}"
displayName="Trying Out!"
displayURL="http://leocth.github.io/" #optional
credits="The Forge Devs, after they caught up with Mojang" #optional
authors="LeoC200"
description='''
This mod is self-describing: YES, this is just a feature testing playground and prototyping board.

Although, you might found something interesting, I don't know :P
'''

[[dependencies.tryingout]] #optional
    modId="forge"
    mandatory=true #mandatory
    versionRange="[26,)"
    ordering="NONE" #BEFORE/AFTER/NONE
    side="BOTH" # BOTH/CLIENT/SERVER

[[dependencies.tryingout]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.2]"
    ordering="NONE"
    side="BOTH"